name: HyPER
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch 
  - torchvision
  - torchaudio
  - pip:
    - torch_geometric
    - torch_scatter
    - torch_sparse
    - torch_cluster
    - torch_spline_conv
    - numpy
    - pandas
    - lightning
    - pytorch-lightning
    - tensorboard
    - jupyterlab
    - uproot
    - awkward
    - h5py
    - pylorentz
    - torch-hep==0.0.4
    - hydra-core
    - rich