dataset:          null
train_set:        null
val_set:          null
train_val_split:  0.9
max_n_events:     -1
drop_last:        False

num_message_layers:   3
hyperedge_order:      3
message_feats:        64
hyperedge_feats:      128
dropout:              0.01

optimizer:            "Adam"
learning_rate:        0.0003
criterion_edge:       "BCE"
criterion_hyperedge:  "BCE"
loss_reduction:       "mean"
alpha:                0.8

epochs:       500
patience:     50
batch_size:   4096

device:       "gpu"
num_devices:   1

savedir: "HyPER_logs"
continue_from_ckpt: null

predict_set:    null
predict_with:   "cpu"
predict_model:  null
predict_output: null
topology: ttbar_allhad

onnx_output:   "HyPER.onnx"
convert_model: null